CREATE TABLE STUDENT(
St_ID NUMERIC(6) PRIMARY KEY CONSTRAINT s_key CHECK (St_ID >0),
Ct_Major CHAR(30),
St_Cohort NUMERIC(4) NOT NULL);

CREATE TABLE EMPLOYEE(
Em_ID NUMERIC(6) PRIMARY KEY CONSTRAINT e_key CHECK (Em_ID > 0),
Em_Office#  CHAR(4) NOT NULL,
Em_Ext#  NUMERIC(4) CONSTRAINT em_key CHECK (Em_Ext# > 1000));

CREATE TABLE COLLEGE(
Cl_Code CHAR(3) PRIMARY KEY,
Cl_Name CHAR(40) NOT NULL,
Cl_Dean CHAR(30));

CREATE TABLE DEPARTMENT(
Dp_Code CHAR(4) PRIMARY KEY,
Dp_Name CHAR(40) NOT NULL,
Dp_HoD CHAR(30),
Dp_Col CHAR(3) CONSTRAINT dp_key FOREIGN KEY (Dp_Col) REFERENCES COLLEGE(Cl_Code));

CREATE TABLE BORROWER(
Br_ID NUMERIC(6) PRIMARY KEY CONSTRAINT b_key CHECK (Br_ID > 0),
Br_Namer CHAR(30) NOT NULL,
Br_Dept CHAR(4) CONSTRAINT br_key FOREIGN KEY (Br_Dept) REFERENCES DEPARTMENT(Dp_Code),
Br_Mobile CHAR(8) CONSTRAINT r_key CHECK (Br_Mobile >=90000000),
Br_City  CHAR(20),
Br_House# CHAR(4),
Br_Type CHAR(1) CONSTRAINT ty_key CHECK (Br_Type IN('S','E')));

SELECT * FROM DEPARTMENT;

CREATE TABLE BOOK(
Bk_ID  NUMERIC(6) PRIMARY KEY CONSTRAINT bk_key CHECK (Bk_ID > 0),
Bk_Title  CHAR(50) NOT NULL,
Bk_Edition  NUMERIC(2),
Bk_#ofPages  NUMERIC(4) CONSTRAINT bok_key CHECK (Bk_#ofPages > 0), 
Bk_TotalCopies NUMERIC(5),
Bk_RemCopies NUMERIC(5));

CREATE TABLE BOOKTOPIC(
Tp_BkID  NUMERIC(6) CONSTRAINT tp_key FOREIGN KEY (Tp_BkID) REFERENCES BOOK(Bk_ID),
Tp_Desc   CHAR(30) NOT NULL);

CREATE TABLE COURSE(
Cr_Code  CHAR(8) PRIMARY KEY,
Cr_Title   CHAR(40) NOT NULL,
Cr_CH   NUMERIC(2) CONSTRAINT cr_key CHECK (Cr_CH > 0),
Cr_#ofSec   NUMERIC(2) CONSTRAINT c_key CHECK (Cr_#ofSec > 0), 
Cr_Dept CHAR(4) CONSTRAINT crd_key FOREIGN KEY (Cr_Dept) REFERENCES DEPARTMENT(Dp_Code));

CREATE TABLE LINK(
Li_CrCode  CHAR(8) CONSTRAINT er_key FOREIGN KEY (Li_CrCode) REFERENCES COURSE(Cr_Code),
Li_BkID  NUMERIC(6) CONSTRAINT er_key FOREIGN KEY (Li_BkID) REFERENCES BOOK(Bk_ID),
Li_usage  CHAR(1) CONSTRAINT li_key CHECK (Li_usage IN('T','R')));

CREATE TABLE REGISTRATION(
Re_BrID   NUMERIC(6)  CONSTRAINT re_key FOREIGN KEY (Re_BrID ) REFERENCES BORROWER(Br_ID),
Re_CrCode   CHAR(8) CONSTRAINT er_key FOREIGN KEY (Re_CrCode) REFERENCES COURSE(Cr_Code),
Re_Semester   CHAR(6)  NOT NULL);

CREATE TABLE ISSUING(
is_BrID  NUMERIC(6) CONSTRAINT re_key FOREIGN KEY (is_BrID ) REFERENCES BORROWER(Br_ID),
is_BkID   NUMERIC(6) CONSTRAINT er_key FOREIGN KEY (is_BkID) REFERENCES COURSE(Cr_Code),
is_DateTaken DATE NOT NULL,
is_DateReturn DATE CHECK (is_DateReturn > is_DateTaken));








